#!/usr/bin/bash

touch {0..12}-main.py 12-pascal_triangle.py 11-student.py 10-student.py 9-student.py 8-class_to_json.py 7-add_item.py 6-load_from_json_file.py 5-save_to_json_file.py 4-from_json_string.py 3-to_json_string.py 2-append_write.py 1-write_file.py 0-read_file.py
